### ISSUE TITLE
indenting selected code doesn't work

### ISSUE THREAD

**Issue by TSlivede** [zhiayang/vscode-tabindentspacealign#1]
Thanks for implementing this extension!

With this plugin enabled, I could no longer indent (or remove indentation from) a selected code block by pressing `tab` (or `shift+tab` respectively).

I could fix this for me by adding `&& !editorHasSelection` to the `When` column for the command `Dynamic Tab` in `File→Preferences→Keyboard Shortcuts`.

It's now:
```
{
  "key": "tab",
  "command": "extension.dynamictabkey",
  "when": "editorTextFocus && !editorHasSelection && !editorReadOnly && !inSnippetMode"
}
```

I would suggest, to add `&& !editorHasSelection` by default, or to implement similar functionality yourself.

**Comment by zhiayang** [comment]
Oh my god, I realise this is literally 1 year late, but somehow i missed this D:

I suppose you've already solved it (thanks for telling me how to, btw!), but i'll push an updated version in a few days!
